version: '3.9'

services:
  gateway:
    image: localhost:5000/tonstorage-gateway:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TON_REPO: https://github.com/ton-blockchain/ton
        TON_BRANCH: testnet
    network_mode: host
    environment:
      TON_STORAGE_ADNL_PORT:
      TON_STORAGE_CONTROL_PORT:
      TON_STORAGE_VERBOSITY_LEVEL:
      TON_PUBLIC_IP:
      TON_STORAGE_GLOBAL_CONFIG: /run/secrets/global-config
      TON_STORAGE_DATABASE_NAME:
      TON_STORAGE_GATEWAY_PORT:
      TON_STORAGE_GATEWAY_DOMAIN:
      TON_STORAGE_GATEWAY_CONFIG: /run/secrets/gateway-config
    secrets:
      - global-config
      - gateway-config

volumes:
  ton-storage-data:

secrets:
  global-config:
    file: ${TON_STORAGE_GLOBAL_CONFIG:?}
  gateway-config:
    file: ${TON_STORAGE_GATEWAY_CONFIG:?}
